const doctor_info = [
  {
    id: 1,
    name: "Dr. Doctor1",
    image: "/images/doctor1.png",
    qualification: "MS",
    experience: "25 years experience",
    department: "Cardio",
    description: "sdfghjxcvbnm wsdfghjnxdcvbn xdcfvbdxfcgvb",
    color: "#E9F3F6",
    value: "true",
  },
  {
    id: 2,
    name: "Dr. Doctor2",
    image: "/images/doctor2.png",
    qualification: "MS",
    experience: "25 years experience",
    department: "Neuro",
    description: "sdfghjxcvbnm wsdfghjnxdcvbn xdcfvbdxfcgvb",
    color: "#ffffff",
    value: "false",
  },
  {
    id: 3,
    name: "Dr. Doctor3",
    image: "/images/doctor.jpg",
    qualification: "MS",
    experience: "25 years experience",
    department: "Gynacology",
    description: "sdfghjxcvbnm wsdfghjnxdcvbn xdcfvbdxfcgvb",
    color: "#E9F3F6",
    value: "true",
  },
  {
    id: 4,
    name: "Dr. Doctor4",
    image: "/images/doctor3.png",
    qualification: "MS",
    experience: "25 years experience",
    department: "Skin",
    description: "sdfghjxcvbnm wsdfghjnxdcvbn xdcfvbdxfcgvb",
    color: "#ffffff",
    value: "false",
  },
  // {
  //   id: 5,
  //   name: "Dr. Doctor5",
  //   image: "/images/doctor.jpg",
  //   qualification: "MS",
  //   experience: "25 years experience",
  //   department: "General physician",
  //   description: "sdfghjxcvbnm wsdfghjnxdcvbn xdcfvbdxfcgvb",
  //   color: "#E9F3F6",
  //   value: "true",
  // },
];

export default doctor_info;
